name: roundmate

services:
  postgres:
    image: "postgres:18"
    environment:
      POSTGRES_DB: roundmate
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "roundmate-postgres-data:/var/lib/postgresql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roundmate -d roundmate"]
      interval: 5s
      timeout: 3s
      retries: 6

volumes:
  roundmate-postgres-data: