spring.application.name=roundmate

# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# DB Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/roundmate
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}